language: julia
julia:
  - nightly
  - 1.3.1
os:
  - osx
  - linux
  - windows

before_script:
  - export PYTHON="" # ensure that PyPlot installs matplotlib using Conda.jl

matrix:
  allow_failures:
    - julia: nightly
codecov: true
