language: julia
julia:
  # - nightly
  - 1.3.1
os:
  - osx
  - linux
  - windows

before_script:
  - export PYTHON="" # ensure that PyPlot installs matplotlib using Conda.jl

matrix:
  # allow_failures:
  #   - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3.1
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
codecov: true
